package com.abrar.BOOKSTORE.config;

import com.abrar.BOOKSTORE.Login.jwt.JwtSecretKeyGenerator;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.env.EnvironmentPostProcessor;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.MapPropertySource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;

/**
 * Makes sure the app always has a real, random JWT signing secret without
 * anyone having to remember to set one.
 *
 * Precedence:
 * 1. If JWT_SECRET is already set (env var, -D flag, etc.) - use that, don't
 * touch anything. Lets anyone who wants explicit control keep it.
 * 2. Otherwise, look for a previously-generated secret in the current user's
 * home directory (outside the project folder entirely, so it can never end
 * up in git even by accident).
 * 3. If neither exists, generate a new 512-bit random secret with
 * SecureRandom (via JwtSecretKeyGenerator), persist it for next time, and
 * use it for this run.
 *
 * Runs as an EnvironmentPostProcessor, which fires before any @Value-based
 * property resolution happens - so by the time JwtTokenProvider reads
 * app.jwtSecret, JWT_SECRET is already populated.
 *
 * One tradeoff worth knowing: tokens signed before a secret rotates (e.g. if
 * you ever delete the secret file) stop validating. Since this app's only
 * consumer of JWTs is the separate /api/auth JSON path - not the normal
 * browser session login - that just means any outstanding API token needs
 * re-issuing, nothing more.
 */
public class JwtSecretEnvironmentPostProcessor implements EnvironmentPostProcessor {

    private static final String PROPERTY_NAME = "JWT_SECRET";
    private static final String SECRET_FILE_NAME = ".bookstore-jwt-secret";

    @Override
    public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
        if (environment.getProperty(PROPERTY_NAME) != null) {
            return; // explicit override already present - respect it
        }
        try {
            String secret = loadOrGenerateSecret();
            MapPropertySource source = new MapPropertySource("jwtAutoGeneratedSecret",
                    Collections.singletonMap(PROPERTY_NAME, secret));
            environment.getPropertySources().addFirst(source);
        } catch (IOException e) {
            // Fall through silently - app.jwtSecret's placeholder default in
            // application.properties still applies, app still starts.
        }
    }

    private String loadOrGenerateSecret() throws IOException {
        Path secretFile = Paths.get(System.getProperty("user.home"), SECRET_FILE_NAME);
        if (Files.exists(secretFile)) {
            String existing = Files.readString(secretFile).trim();
            if (!existing.isBlank()) {
                return existing;
            }
        }
        String generated = JwtSecretKeyGenerator.generateSecretKey();
        Files.writeString(secretFile, generated);
        return generated;
    }
}